version: '3'

services:
  whoami:
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`www.lixud.com`)"

networks:
  default:
    external:
      name: traefik_default
